### ISSUE TITLE
getting the  trace  while running with  -lf  flag

### ISSUE THREAD

**Issue by Zubrania** [wtsi-ssg/pcp#30]
Hello  Team

I am getting  the following  trace  while  trying to do pcp  to lustre  FS

without -lf  flag   pcp works   as expected

env python 2.7
pcp from git 

Thank  you 

Tue Mar 20 17:09:19 2018<stdout>:WARNING: appears to have problems with openmpi on
Tue Mar 20 17:09:19 2018<stdout>:large job sizes; if pcp hangs, consider using mpich
Tue Mar 20 17:09:19 2018<stdout>:instead.
Tue Mar 20 17:09:19 2018<stdout>:R0: All workers have reported in.
Tue Mar 20 17:09:19 2018<stdout>:Starting 32 processes.
Tue Mar 20 17:09:19 2018<stdout>:Files larger than 500 Mbytes will be copied in parallel chunks.
Tue Mar 20 17:09:19 2018<stdout>:Will force stripe all files.
Tue Mar 20 17:09:19 2018<stdout>:Will md5 verify copies.
Tue Mar 20 17:09:19 2018<stdout>:
Tue Mar 20 17:09:19 2018<stdout>:Starting phase I: Scanning and copying directory structure...
Tue Mar 20 17:09:19 2018<stdout>:Exception on rank 0 host node25:
Tue Mar 20 17:09:19 2018<stdout>:Traceback (most recent call last):
Tue Mar 20 17:09:19 2018<stdout>:  File "/usr/bin/pcp", line 1533, in <module>
Tue Mar 20 17:09:19 2018<stdout>:    scantree(sourcedir, destdir, statedb)
Tue Mar 20 17:09:19 2018<stdout>:  File "/usr/bin/pcp", line 354, in scantree
Tue Mar 20 17:09:19 2018<stdout>:    listofpaths = walker.Execute(sourcedir)
Tue Mar 20 17:09:19 2018<stdout>:  File "/usr/local/lib/python2.7/site-packages/pcplib/parallelwalk.                                                          py", line 260, in Execute
Tue Mar 20 17:09:19 2018<stdout>:    self._ProcessNode()
Tue Mar 20 17:09:19 2018<stdout>:  File "/usr/local/lib/python2.7/site-packages/pcplib/parallelwalk.                                                          py", line 175, in _ProcessNode
Tue Mar 20 17:09:19 2018<stdout>:    self.ProcessDir(filename)
Tue Mar 20 17:09:19 2018<stdout>:  File "/usr/bin/pcp", line 1345, in ProcessDir
Tue Mar 20 17:09:19 2018<stdout>:    copyDir(directoryname, newdir)
Tue Mar 20 17:09:19 2018<stdout>:  File "/usr/bin/pcp", line 1042, in copyDir
Tue Mar 20 17:09:19 2018<stdout>:    layout = lustreapi.getstripe(sourcedir)
Tue Mar 20 17:09:19 2018<stdout>:  File "/usr/local/lib/python2.7/site-packages/pcplib/lustreapi.py"                                                          , line 121, in getstripe
Tue Mar 20 17:09:19 2018<stdout>:    raise IOError(err, os.strerror(err))
Tue Mar 20 17:09:19 2018<stdout>:IOError: [Errno 25] Inappropriate ioctl for device

**Comment by guycoates** [comment]
Hi,
That means that the source directory is not a lustre filesystem, and so there is no stripe information to copy.

**Comment by Zubrania** [comment]
Hi,  according to documentation  I  have  found here  “-lf can be used when only the destination filesystem is lustre.”

That kind of error expected using “-l requires that the source and destination filesystems are both lustre."

In my  case only  destination file system  is Lustre while source file system  is not

**Comment by Zubrania** [comment]
Thank  you 

already  done  that using that workaround
